name: Test IPCS solvers

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Flake8 code
        run: python3 -m flake8 .

      - name: Type-checking
        run: python3 -m mypy .

      - name: Run Taylor-Green problem
        run: python3 ipcs.py --spatial=4 --temporal=2

      - name: Run create DFG meshes
        run: |
          python3 create_and_convert_3D_mesh.py
          python3 create_and_convert_2D_mesh.py

      - name: Run DFG (2D)
        run: python3 DFG_benchmark.py

      - name: Run DFG (3D)
        run: mpirun -n 2 python3 DFG_benchmark.py --3D
