name: Test IPCS solvers

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-22.04
    container: dolfinx/dolfinx:nightly
    steps:
      - uses: actions/checkout@v2
    
      - name: Flake8 code
        run: flake8 .
      - name: Install dependencies
        run: |
          pip3 install tqdm
      - name: Run test
        run: |
          python3 ipcs.py
          python3 create_and_convert_3D_mesh.py
          python3 create_and_convert_2D_mesh.py
          python3 DFG_benchmark.py
          mpirun -n 2 python3 DFG_benchmark.py --3D
